### PR TITLE
Body, Url Added

### PR DESCRIPTION
**Pull request by end3r-man**
Add the doc about the body, and the url

### CODE REVIEW

**Comment by Log1x** [comment]
Thank you! `->body()` is already at the bottom of [Basic Usage](https://laracord.com/docs/messages#content-basic-usage) though 👀 – perhaps it should be moved? I was thinking of expanding the section up there that might make it more notice-able though with the addition of the methods from #94

**Comment by Log1x** [comment]
Actually let's keep it, but move it below `->content()` on the page and table of contents. Also if you wouldn't mind capitalizing `URL` in the table of contents, then this is good to go. 😊

**Comment by end3r-man** [comment]
`` ->body() `` as u mention right now im see the body in the docs so in my point its nice to have in the list easy to notice

**Comment by end3r-man** [comment]
> Actually let's keep the second mention of `->body()`, but move it below `->content()` on the page and table of contents. Also if you wouldn't mind capitalizing `URL` in the table of contents, then this is good to go. 😊

no problem ill update it

**Comment by end3r-man** [comment]
moved the body under the content  and caps the Url in the list

**Pull request merged**
